application: chalis 
version: 1
runtime: python27
api_version: 1
threadsafe: false

libraries:                                                                      
- name: jinja2                                                                  
  version: latest  

handlers:
- url: .*/css
  static_dir: css

- url: .*/js
  static_dir: js

- url: .*/images
  static_dir: images

- url: .*/fonts
  static_dir: fonts

- url: /qunit
  static_dir: test/qunit

- url: /test.*
  script: gaeunit.py

- url: /.*
  script: chalis.app
