application: chalis 
version: 1
runtime: python27
api_version: 1
threadsafe: false

libraries:                                                                      
- name: jinja2                                                                  
  version: latest  

handlers:
- url: /test.*
  script: gaeunit.py

- url: /.*
  script: chalis.app
